unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-s

unbind '"'
bind '"' split-window -v -c "#{pane_current_path}"
unbind %
bind % split-window -h -c "#{pane_current_path}"

set -g pane-border-style "fg=#45475a"
set -g pane-active-border-style "fg=#ea9a97"
set -g pane-border-lines single
set -g pane-border-indicators off
set -g pane-border-status top
set -g pane-border-format "#{?pane_active,#[bg=default fill=default fg=#ea9a97]─,#[bg=default fill=default]}"

bind -T copy-mode WheelUpPane send -N 1 -X scroll-up
bind -T copy-mode WheelDownPane send -N 1 -X scroll-down
bind -T copy-mode-vi WheelUpPane send -N 1 -X scroll-up
bind -T copy-mode-vi WheelDownPane send -N 1 -X scroll-down

# Copy selection without snapping to bottom (press q to exit copy mode)
bind -T copy-mode MouseDragEnd1Pane send -X copy-selection
bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-selection



# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
is_vim="children=(); i=0; pids=( $(ps -o pid= -t '#{pane_tty}') ); \
while read -r c p; do [[ -n c && c -ne p && p -ne 0 ]] && children[p]+=\" $\{c\}\"; done <<< \"$(ps -Ao pid=,ppid=)\"; \
while (( $\{#pids[@]\} > i )); do pid=$\{pids[i++]\}; pids+=( $\{children[pid]-\} ); done; \
ps -o state=,comm= -p \"$\{pids[@]\}\" | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h' { if -F '#{pane_at_left}'   '' 'select-pane -L' }
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j' { if -F '#{pane_at_bottom}' '' 'select-pane -D' }
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k' { if -F '#{pane_at_top}'    '' 'select-pane -U' }
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l' { if -F '#{pane_at_right}'  '' 'select-pane -R' }
tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"

bind-key -T copy-mode-vi 'C-h' if -F '#{pane_at_left}'   '' 'select-pane -L'
bind-key -T copy-mode-vi 'C-j' if -F '#{pane_at_bottom}' '' 'select-pane -D'
bind-key -T copy-mode-vi 'C-k' if -F '#{pane_at_top}'    '' 'select-pane -U'
bind-key -T copy-mode-vi 'C-l' if -F '#{pane_at_right}'  '' 'select-pane -R'

set -g focus-events on
set -g cursor-colour "#ffffff"
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB,*:Ss=\033[%p1%d q:Se=\033[2 q:Cs=\033]12;%p1%s\007:Cr=\033]112\007"

set -g mouse on
set-option -g status-position top
set -g status-justify centre
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
# set -g 'status-format[1]' ' '
# set -g status-right "#[fg=white]%m/%d/%Y %I:%M %p"
set -g status-right ""
# set -g window-status-current-format '#I:#W'
# set -g window-status-format '#I:#W'
set -g window-status-current-format '#[bold, fg=#ea9a97 ]#I:#W'
set -g window-status-format '#I:#W'

set -g @plugin 'tmux-plugins/tpm'
# set -g @plugin 'christoomey/vim-tmux-navigator'


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
set -g status-style bg=default
